### ISSUE TITLE
Configuration pages for login, lobby and chatroom

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-fe-next#10]
### Description
In order to identify what's pages belong to each module, we identified 3 pages.

- Login (Authentication page for guest user or github users)
- Lobby (Display all the chat rooms created)
- Chat Room (Display the chat room that user joined)

### Tasks

- [ ] Create Authentication page -> /auth
- [ ] Create Lobby page -> /lobby
- [ ] Create Chatroom page -> /chatroom/[id]

### Technical specs
Authentication page should be accessible for users who doesn't logged.
Lobby page must be accessible for users who already logged
Chatroom page must be accessible for users who already logged
