### ISSUE TITLE
Send messages into chat room

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-fe-next#25]
### Description
When a user join into a chatroom, should be able to send message and receive them in real time

### Tasks

- [x] Display all the messages
- [x] Display a message if there are no messages
- [x] Allow to send message
- [x] Allow to receive message in real time
