### ISSUE TITLE
Authentication with Github Account

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-fe-next#4]
### Description

User can be able to login to the application with their Github Account

### Tasks

- [ ] When user click to Github Login button should be redirect to application
- [ ] Register user into database
- [ ] Add a callback page that redirect to the application
- [x] If user is already logged, should be redirect to application
