### ISSUE TITLE
Create a chat room

### ISSUE THREAD

**Issue by JairHuamanBellido** [JairHuamanBellido/realz-fe-next#7]
### Description

When an user authenticated with their github account, should be able to create a room.

### Tasks

- [x] Shows a button for create a chat room
- [x] Complete all the required fields for create a chatroom
- [x] Show an successfully message 
- [x] Redirect to Chatroom page
